# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c98ffeeb31170f893f66efa4913029f6b3a687f7b542ed932d785b5586c70da5cc3f0e442a9250a5d0fc59ad0bc3ab750bbc63825aa7069322fe2bacc3addeb2

test:
  secret_key_base: 62c1e510ea627643a687780f3b608fc895e138b82804779cb8ca4cab839e25e1a9f39c2144877ff4122fbdfa116c498e4eb3086658d1ac0868b360e118e9f0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a9e97dcccf8150393cee978d783ca462c4d935a37c71f2fe915f05f881c36249581fadc7c1850f9b3eb85b974af6be35479fc8f5f8253d3a075bb2697970b485
